The ldap_type variable not have the self
I running script and received the error at ldap_type not exist Global variable. I changed by adding "self" on front variable.

Traceback (most recent call last):
  File "change_config.py", line 48, in <module>
    r = name_changer.startup()
  File "/root/change_gluu_host.py", line 162, in startup
    if ldap_type == 'openldap':
NameError: global name 'ldap_type' is not defined